---
abstract: 'throw HTTP-Errors as (Exception::Class-) Exceptions'
author:
  - 'Thomas Müller <tmueller@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Exception
requires:
  Exception::Class: 1.29
  HTTP::Status: 5.817
  Scalar::Util: 1.22
  Test::Exception: 0.29
  Test::More: 0.88
  Test::NoWarnings: 1.04
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/tmueller/http_exception/issues
  repository: git://github.com/tmueller/http_exception.git
version: 0.04004
