---
abstract: 'throw HTTP-Errors as (Exception::Class-) Exceptions'
author:
  - 'Thomas Mueller <tmueller@cpan.org>'
build_requires:
  Test::Exception: 0.29
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Exception
provides:
  HTTP::Exception:
    file: lib/HTTP/Exception.pm
    version: 0.03000
  HTTP::Exception::1XX:
    file: lib/HTTP/Exception/1XX.pm
    version: 0.03000
  HTTP::Exception::2XX:
    file: lib/HTTP/Exception/2XX.pm
    version: 0.03000
  HTTP::Exception::3XX:
    file: lib/HTTP/Exception/3XX.pm
    version: 0.03000
  HTTP::Exception::4XX:
    file: lib/HTTP/Exception/4XX.pm
    version: 0.03000
  HTTP::Exception::5XX:
    file: lib/HTTP/Exception/5XX.pm
    version: 0.03000
  HTTP::Exception::Base:
    file: lib/HTTP/Exception/Base.pm
    version: 0.03000
  HTTP::Exception::Loader:
    file: lib/HTTP/Exception/Loader.pm
    version: 0.03000
requires:
  Exception::Class: 1.29
  HTTP::Status: 5.817
  Scalar::Util: 1.22
  base: 0
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03000
