---
abstract: 'throw HTTP-Errors as (Exception::Class-) Exceptions'
author:
  - 'Thomas Müller <tmueller@cpan.org>'
build_requires:
  HTTP::Exception::200: 0
  HTTP::Exception::405: 0
  HTTP::Request::Common: 0
  Plack::Middleware::HTTPExceptions: 0
  Plack::Test: 0
  Test::Exception: 0
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Exception
requires:
  Exception::Class: 0
  Exception::Class::Base: 0
  HTTP::Status: 0
  Scalar::Util: 0
  base: 0
  strict: 0
version: 0.04
